# Generated by Django 2.1.5 on 2019-03-16 13:08

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('app1', '0002_auto_20190316_1833'),
    ]

    operations = [
        migrations.CreateModel(
            name='Answer',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('answerIs', models.TextField(blank=True, null=True)),
                ('answereddDateTime', models.DateTimeField(auto_now_add=True)),
                ('answeredBy', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='app1.MyUser')),
            ],
        ),
        migrations.CreateModel(
            name='Questions',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('questionIs', models.TextField(blank=True, null=True)),
                ('askedDateTime', models.DateTimeField(auto_now_add=True)),
                ('askedBy', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='app1.MyUser')),
            ],
        ),
        migrations.AddField(
            model_name='answer',
            name='questionId',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='app1.Questions'),
        ),
    ]
