# Generated by Django 2.1.5 on 2019-04-23 07:04

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('app1', '0004_questions_total_view'),
    ]

    operations = [
        migrations.CreateModel(
            name='UpcomingEvents',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('eventTitle', models.CharField(blank=True, max_length=200, null=True)),
                ('eventDescription', models.TextField(blank=True, null=True)),
                ('createdDateTime', models.DateTimeField(auto_now_add=True)),
                ('addedBy', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='app1.MyUser')),
            ],
        ),
    ]
