# Generated by Django 2.1.5 on 2019-04-23 08:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app1', '0007_ngointerest'),
    ]

    operations = [
        migrations.AddField(
            model_name='questions',
            name='total_answer',
            field=models.IntegerField(default=0),
        ),
    ]
